-- Add missing Bedfordshire location pages so butchers can appear
-- Run this in Supabase SQL Editor

INSERT INTO public_locations (
  id,
  name,
  slug,
  type,
  county_slug,
  full_path,
  seo_title,
  seo_description,
  meta_description,
  h1_title,
  intro_text,
  main_content,
  faq_content,
  butcher_count,
  seo_keywords
) VALUES
(
  gen_random_uuid(),
  'Flitwick',
  'flitwick',
  'town',
  'bedfordshire',
  'bedfordshire/flitwick',
  'Best Butchers in Flitwick, Bedfordshire | Butchers Near Me',
  'Find the finest butchers in Flitwick, Bedfordshire. Quality meat, expert service, and local favorites.',
  'Discover quality butchers in Flitwick, Bedfordshire. Local meat specialists offering fresh cuts, expert advice, and exceptional service.',
  'Best Butchers in Flitwick, Bedfordshire',
  'Looking for quality butchers in Flitwick? Our directory features the best local meat specialists in this charming Bedfordshire town.',
  'Flitwick is home to excellent butchers who serve the local community with pride. These skilled professionals offer premium cuts of meat, expert preparation, and personalized service that keeps customers coming back.',
  '{"questions": [{"question": "What types of meat do Flitwick butchers offer?", "answer": "Flitwick butchers typically offer beef, pork, lamb, poultry, and often specialty items like game meats and homemade sausages."}, {"question": "Do butchers in Flitwick offer local sourcing?", "answer": "Many Flitwick butchers work with local farms to provide fresh, locally-sourced meat products."}]}',
  0,
  ARRAY['flitwick butchers', 'meat shops flitwick', 'butchers bedfordshire', 'local butchers flitwick', 'fresh meat flitwick']
),
(
  gen_random_uuid(),
  'Great Barford',
  'great-barford',
  'town',
  'bedfordshire',
  'bedfordshire/great-barford',
  'Best Butchers in Great Barford, Bedfordshire | Butchers Near Me',
  'Find the finest butchers in Great Barford, Bedfordshire. Quality meat, expert service, and local favorites.',
  'Discover quality butchers in Great Barford, Bedfordshire. Local meat specialists offering fresh cuts, expert advice, and exceptional service.',
  'Best Butchers in Great Barford, Bedfordshire',
  'Looking for quality butchers in Great Barford? Our directory features the best local meat specialists in this picturesque Bedfordshire town.',
  'Great Barford''s butchers are known for their exceptional quality and traditional approach to meat preparation. These local specialists serve the community with fresh, high-quality products.',
  '{"questions": [{"question": "Are there traditional butchers in Great Barford?", "answer": "Yes, Great Barford has traditional butchers who use time-honored techniques and offer personalized service."}, {"question": "Do Great Barford butchers offer custom cuts?", "answer": "Most butchers in Great Barford are happy to provide custom cuts and special preparations for their customers."}]}',
  0,
  ARRAY['great barford butchers', 'meat shops great barford', 'butchers bedfordshire', 'local butchers great barford', 'town butcher']
),
(
  gen_random_uuid(),
  'Kempston',
  'kempston',
  'town',
  'bedfordshire',
  'bedfordshire/kempston',
  'Best Butchers in Kempston, Bedfordshire | Butchers Near Me',
  'Find the finest butchers in Kempston, Bedfordshire. Quality meat, expert service, and local favorites.',
  'Discover quality butchers in Kempston, Bedfordshire. Local meat specialists offering fresh cuts, expert advice, and exceptional service.',
  'Best Butchers in Kempston, Bedfordshire',
  'Looking for quality butchers in Kempston? Our directory features the best local meat specialists in this bustling Bedfordshire town.',
  'Kempston''s butchers serve the local community with dedication and expertise. From traditional cuts to specialty items, these professionals provide excellent service and quality products.',
  '{"questions": [{"question": "What services do Kempston butchers provide?", "answer": "Kempston butchers offer fresh meat cuts, specialty preparations, and often catering services for local events."}, {"question": "Can I order ahead from Kempston butchers?", "answer": "Many Kempston butchers accept advance orders, especially for special occasions or large quantities."}]}',
  0,
  ARRAY['kempston butchers', 'meat shops kempston', 'butchers bedfordshire', 'local butchers kempston', 'fresh meat kempston']
),
(
  gen_random_uuid(),
  'Westoning',
  'westoning',
  'town',
  'bedfordshire',
  'bedfordshire/westoning',
  'Best Butchers in Westoning, Bedfordshire | Butchers Near Me',
  'Find the finest butchers in Westoning, Bedfordshire. Quality meat, expert service, and local favorites.',
  'Discover quality butchers in Westoning, Bedfordshire. Local meat specialists offering fresh cuts, expert advice, and exceptional service.',
  'Best Butchers in Westoning, Bedfordshire',
  'Looking for quality butchers in Westoning? Our directory features the best local meat specialists in this charming Bedfordshire town.',
  'Westoning may be a small town, but it values quality when it comes to local butchers. These specialists provide excellent service and fresh, high-quality meat products.',
  '{"questions": [{"question": "Are there local butchers serving Westoning?", "answer": "Yes, Westoning has access to quality local butchers who serve the town and surrounding areas."}, {"question": "What makes Westoning butchers special?", "answer": "Westoning butchers are known for their personal service and commitment to quality, typical of small town businesses."}]}',
  0,
  ARRAY['westoning butchers', 'meat shops westoning', 'butchers bedfordshire', 'local butchers westoning', 'town butcher westoning']
),
(
  gen_random_uuid(),
  'Wilden',
  'wilden',
  'town',
  'bedfordshire',
  'bedfordshire/wilden',
  'Best Butchers in Wilden, Bedfordshire | Butchers Near Me',
  'Find the finest butchers in Wilden, Bedfordshire. Quality meat, expert service, and local favorites.',
  'Discover quality butchers in Wilden, Bedfordshire. Local meat specialists offering fresh cuts, expert advice, and exceptional service.',
  'Best Butchers in Wilden, Bedfordshire',
  'Looking for quality butchers in Wilden? Our directory features the best local meat specialists serving this small Bedfordshire town.',
  'Wilden''s butchers provide essential services to this small Bedfordshire community. These local specialists ensure residents have access to fresh, quality meat products.',
  '{"questions": [{"question": "Do butchers serve the Wilden area?", "answer": "Yes, there are butchers who serve Wilden and the surrounding Bedfordshire towns."}, {"question": "Can I find specialty meats near Wilden?", "answer": "Local butchers serving Wilden often offer specialty cuts and products beyond standard offerings."}]}',
  0,
  ARRAY['wilden butchers', 'meat shops wilden', 'butchers bedfordshire', 'local butchers wilden', 'town butcher wilden']
);